- name: Create folders
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ folder_to_create }}"
  tags: [folder]

- name: Create files
  file:
    path: "{{ item.path }}"
    state: touch
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ file_to_create }}"
  tags: [file]
