---
- name: Enable jenkins
  service:
    name: jenkins
    enabled: yes
    
- name: Start jenkins
  service:
    name: jenkins
    state: started
        
- name: Reload Daemon
  systemd:
    daemon_reload: yes
